name: Telegram Notification

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram message
        run: |
          response=$(curl -s -w "%{http_code}" -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d text="New push to the repository: $GITHUB_REPOSITORY by $GITHUB_ACTOR" -o response.json)
          
          # Check for success response
          http_code=$(echo "$response" | tail -n1)
          if [ "$http_code" -ne 200 ]; then
            echo "Error sending message to Telegram. HTTP Code: $http_code"
            echo "Response: $(cat response.json)"
            exit 1
          fi
          
          echo "Message sent successfully!"
