name: Telegram Notification

on:
  push:
    branches:
      - main  # You can change this to any branch you want to monitor

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram message
        run: |
          curl -s -X POST "https://api.telegram.org/bot$TOKEN/sendMessage" \
          -d chat_id=$CHAT_ID \
          -d text="New push to the repository: $GITHUB_REPOSITORY by $GITHUB_ACTOR"
        env:
          TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
