name: Telegram Notification

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  notify:
    runs-on: ubuntu-22.04  # Or you can use ubuntu-24.04

    steps:
      - name: Send Telegram message
        run: |
          MESSAGE="🚀 A new commit has been pushed to the main branch."
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -H "Content-Type: application/json" \
            -d "{\"chat_id\": \"${{ secrets.TELEGRAM_CHAT_ID }}\", \"text\": \"$MESSAGE\"}"
